const fs=require('node:fs'),assert=require('node:assert/strict'),ts=require('typescript');
function compile(path,deps={}){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText)(n=>deps[n]??require(n),m,m.exports);return m.exports}
const c=compile('lib/cabinet.ts',{'./schema.json':require('../lib/schema.json'),'./engine-sources.json':require('../lib/engine-sources.json')}),u=compile('lib/units.ts'),p=compile('lib/projects.ts',{'./cabinet':c}),m=compile('lib/manufacturing.ts'),a=compile('lib/assembly.ts',{'./cabinet':c,'./manufacturing':m,'./units':u,'./diagram-depth':compile('lib/diagram-depth.ts')}),s=compile('lib/settings.ts');
for(let family=0;family<6;family++)for(const starter of c.schemas[family].starters){const values=c.starterValues(family,starter.id),d={version:2,engine:29,displayUnits:'in',family,name:starter.name,values},restored=p.parseDesign(d);assert.equal(restored.displayUnits,'in');for(const f of c.schemas[family].fields)if(f.key!=='cabinet_preset')assert.deepEqual(restored.values[f.key],values[f.key],f.key)}
const d=p.parseDesign({version:2,engine:29,family:0,values:c.defaults(0)});
assert.throws(()=>p.parseDesign({...d,family:9}));assert.throws(()=>p.parseDesign({...d,values:{...d.values,mixed_bay_types:[{bad:'object'}]}}));
let records=[];for(let i=0;i<12;i++)records=p.upsertRecent(records,{id:String(i),updated:'2026-09-15',design:d});assert.equal(records.length,10);assert.equal(records[0].id,'11');records=p.upsertRecent(records,{...records[5],updated:'2026-09-16'});assert.equal(records.length,10);assert.equal(records[0].id,'6');assert.equal(p.recentRecords(JSON.stringify(records)).length,10);assert.deepEqual(p.recentRecords(JSON.stringify([{id:'bad',updated:'x',design:{}}])),[]);
const field=k=>c.schemas[0].fields.find(f=>f.key===k);assert(s.inactiveReason(field('worktop_thickness'),{...d.values,include_worktop:false}));assert(!s.inactiveReason(field('worktop_thickness'),{...d.values,include_worktop:true}));assert(s.inactiveReason(field('target_module_pitch_x'),{...d.values,width_basis:'drawer_inside',target_dimension_mode:'direct'}));
const text=['ECHO: "BOM|CS-L|1|carcass|PLY|18|500|700|side"','ECHO: "BOM|CS-R|1|carcass|PLY|18|500|700|side"','ECHO: "BOM|BOTTOM|1|carcass|PLY|18|614|500|butt"','ECHO: "BOM|B1-D1-SL|1|drawer_side|PLY|12|400|120|butt"','ECHO: "BOM|B1-D1-FR|1|drawer_front|PLY|12|380|120|butt"','ECHO: "DIM|CABINET|W=650|H=700|D=500"','ECHO: "WARN|Check <stock>"'].join('\n');
const html=a.assemblyPacket('<img src=x onerror=alert(1)>',d.values,text,'in');assert(!html.includes('<img src=x'));assert(html.includes('&lt;img'));assert(html.includes('CS-L'));assert(html.includes('B1-D1-SL'));assert(html.includes('25.59'));assert(!html.includes('NaN'));assert(html.includes('Print / Save as PDF'));assert.equal(m.parseManufacturing(text+'\n'+text).bom.length,5);assert.equal(m.parseManufacturing(text).warnings.length,1);assert(m.operationNotes('ECHO: "BACK face depth 6"').length);
console.log('Recipe recovery, invalid input rejection, recent retention, settings relevance, manufacturing parsing, matching packet IDs and HTML escaping passed.');
