const fs=require('fs'),assert=require('assert/strict'),ts=require('typescript');
function compile(path,deps={}){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText)(n=>deps[n]??require(n),m,m.exports);return m.exports}
const c=compile('lib/cabinet.ts',{'./schema.json':require('../lib/schema.json'),'./engine-sources.json':require('../lib/engine-sources.json')}),m=compile('lib/manufacturing.ts'),u=compile('lib/units.ts'),a=compile('lib/assembly.ts',{'./cabinet':c,'./manufacturing':m,'./units':u,'./diagram-depth':compile('lib/diagram-depth.ts')}),p=compile('lib/projects.ts',{'./cabinet':c}),hardware=require('../lib/hardware.json');
assert.equal(c.families.length,6);const targets=['shop_cart','utility','benchtop','stackable','kitchen','drawer'];let count=0;
for(let i=0;i<6;i++){for(const r of c.schemas[i].starters){const v=c.starterValues(i,r.id);assert.deepEqual(c.validate(v),[],r.id);assert(c.geometry(v,false,false).every(p=>[p.x,p.y,p.z,p.w,p.d,p.h].every(Number.isFinite)));count++}for(const profile of hardware.profiles.filter(p=>p.targets.includes(targets[i])))for(const [key,value]of Object.entries(profile.apply)){const f=c.schemas[i].fields.find(f=>f.key===key);assert(f,key);if(f.options)assert(f.options.includes(String(value)),key)}}
const old={version:2,engine:29,family:4,values:{...c.defaults(4),cabinet_nominal_depth:712.345678},name:'Kitchen'};assert.equal(p.parseDesign(old).values.cabinet_nominal_depth,712.345678);assert.equal(p.parseDesign(old).engine,32);
const drawer=c.defaults(5),text=['ECHO: "BOM|D1-SL|1|drawer_side|DRAWER_WALL|12|478|120|butt"','ECHO: "BOM|D1-SR|1|drawer_side|DRAWER_WALL|12|478|120|butt"','ECHO: "BOM|D1-BOT|1|drawer_bottom|DRAWER_BOTTOM|6|400.6|454|butt"','ECHO: "DIM|DRAWER|OUTSIDE|W=424.6|D=478|H=120"'].join('\n');const packet=a.assemblyPacket('Drawer',drawer,text);assert(packet.includes('D1 · drawer assembly'));assert(packet.includes('>D1-SL</text>'));assert(!packet.includes('Dry-fit the carcass'));assert.equal(c.defaults(3).bottom_tab_placement,'stack_safe');
for(const key of ['metal_slide_cabinet_holes_x','metal_slide_drawer_holes_x','drawer_module_pitch_x'])assert(u.isLengthField(c.schemas[5].fields.find(f=>f.key===key)));assert(!u.isLengthField(c.schemas[5].fields.find(f=>f.key==='drawer_module_count_x')));
console.log(count+' defaults/recipes, 16 hardware patches, old-design preservation, drawer packets, stack-safe defaults and unit classification passed.');
