'use client';
import {Values} from '@/lib/cabinet';
import {Units} from '@/lib/units';
import DimensionInput from './DimensionInput';
import {Switch} from '@/components/ui/switch';
export default function FitGuide({family,values:v,units,change,patch}:{family:number;values:Values;units:Units;change:(k:string,v:any)=>void;patch:(v:Values)=>void}){
 const active=v.width_basis==='drawer_inside'||v.depth_basis==='drawer_inside';
 const dimension=(key:string,title:string)=><label className='guide-field'>{title}<DimensionInput id={'guide-'+key} units={units} value={v[key]} onChange={n=>change(key,n)}/></label>;
 return <section className='fit-guide'><h3>What should this cabinet fit?</h3><div className='manufacturing-actions'><button className={!active?'primary':''} onClick={()=>patch({width_basis:'outside',depth_basis:'outside'})}>An available space</button><button className={active?'primary':''} onClick={()=>patch({width_basis:'drawer_inside',depth_basis:'drawer_inside'})}>Objects in drawers</button></div>{!active?<><p>Enter the cabinet envelope. Allow installation clearance before entering the available size.</p>{dimension('cabinet_width','Outside width')}{dimension('cabinet_height','Outside height')}{dimension(family===4?'cabinet_nominal_depth':'cabinet_depth',family===4?'Finished depth':'Carcass depth')}<small>Worktop overhangs and base hardware may extend beyond the carcass.</small></>:<><p>OpenSCAD adjusts width and depth around the selected drawer bank. Height remains an outside dimension.</p><label className='guide-field'>Drawer bank (starting at 1)<input type='number' min='1' step='1' value={v.target_drawer_bank} onChange={e=>{if(Number.isInteger(e.target.valueAsNumber)&&e.target.valueAsNumber>0)change('target_drawer_bank',e.target.valueAsNumber)}}/></label>{['width','depth'].map(axis=><label className='advanced-control' key={axis}><Switch checked={v[axis+'_basis']==='drawer_inside'} onCheckedChange={on=>change(axis+'_basis',on?'drawer_inside':'outside')}/>Fit drawer {axis}</label>)}<label className='advanced-control'><Switch checked={v.target_dimension_mode==='modular_grid'} onCheckedChange={on=>change('target_dimension_mode',on?'modular_grid':'direct')}/>Use a modular grid</label>{v.target_dimension_mode==='modular_grid'?<>{dimension('target_module_pitch_x','Module width')}{dimension('target_module_pitch_y','Module depth')}{['x','y'].map(axis=><label className='guide-field' key={axis}>Module count {axis}<input type='number' min='1' step='1' value={v['target_module_count_'+axis]} onChange={e=>{if(Number.isInteger(e.target.valueAsNumber)&&e.target.valueAsNumber>0)change('target_module_count_'+axis,e.target.valueAsNumber)}}/></label>)}{dimension('target_module_edge_clearance_x','Width edge clearance')}{dimension('target_module_edge_clearance_y','Depth edge clearance')}</>:<>{v.width_basis==='drawer_inside'&&dimension('target_drawer_inside_width','Required drawer inside width')}{v.depth_basis==='drawer_inside'&&dimension('target_drawer_inside_depth','Required drawer inside depth')}</>}<label className='advanced-control'><Switch checked={v.target_dimension_policy==='exact'} onCheckedChange={on=>change('target_dimension_policy',on?'exact':'minimum')}/>Resize exactly to target</label><small>{v.target_dimension_policy==='exact'?'Cabinet may grow or shrink.':'Minimum sizing grows the cabinet only; a larger existing size stays larger.'} Use Calculate fitted size above the preview to see the result.</small></>}</section>
}
