'use client';
import {useState} from 'react';
import catalog from '@/lib/hardware.json';
import equipmentCatalog from '@/lib/equipment-hardware.json';
import {Values} from '@/lib/cabinet';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
export default function HardwarePicker(props:{family:number;query?:string;apply:(patch:Values)=>void}){return <div className='hardware-presets'>{(['drawer_slide','hinge'] as const).map(category=><HardwareCategory key={props.family+'-'+category} {...props} category={category}/>)}</div>}
function HardwareCategory({family,apply,query='',category}:{family:number;query?:string;apply:(patch:Values)=>void;category:'drawer_slide'|'hinge'}){
 const target=['shop_cart','utility','benchtop','stackable','kitchen','drawer','equipment_stand'][family],profiles=(family===6?equipmentCatalog.profiles:catalog.profiles).filter(p=>p.category===category&&(!p.targets||p.targets.includes(target)));
 const matching=profiles.filter(p=>[p.label,p.manufacturer,p.family,p.model].join(' ').toLowerCase().includes(query.toLowerCase()));
 const [id,setId]=useState('');const profile=profiles.find(p=>p.id===id);
 return <section className='hardware-picker'><p>Apply a hardware preset once, then freely edit its dimensions and drilling settings.</p><h3>{category==='hinge'?'Hinges':'Drawer slides'}</h3><Select value={profile?.id??''} onValueChange={setId}><SelectTrigger className='choice' aria-label={category==='hinge'?'Hinge preset':'Drawer slide preset'}><SelectValue placeholder={category==='hinge'?'Choose a hinge…':'Choose a drawer slide…'}/></SelectTrigger><SelectContent>{matching.map(p=><SelectItem key={p.id} value={p.id}>{p.label}</SelectItem>)}</SelectContent></Select>{!matching.length&&<p>No matching presets for this category and cabinet family.</p>}{profile&&<><h3>{profile.manufacturer} · {profile.family}</h3><p>{profile.model}</p><p><strong>Catalog status:</strong> {profile.verification.status.replaceAll('_',' ')}</p><p>{profile.verification.notes}</p>{'url' in profile.source&&typeof profile.source.url==='string'&&/^https:\/\//.test(profile.source.url)&&<a target='_blank' rel='noreferrer' href={profile.source.url}>Catalog source document</a>}<details><summary>Settings this preset changes ({Object.keys(profile.apply??{}).length})</summary><dl>{Object.entries(profile.apply??{}).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{JSON.stringify(v)}</dd></div>)}</dl><small>Source lengths are in millimeters.</small></details><button className='primary' disabled={!Object.keys(profile.apply??{}).length} onClick={()=>apply(profile.apply??{})}>{Object.keys(profile.apply??{}).length?category==='hinge'?'Apply hinge preset':'Apply drawer slide preset':'Reference only — no settings available'}</button><p>Existing settings outside this patch are retained. Manufacturer-partial profiles may intentionally disable unsupported drilling.</p></>}</section>
}
