'use client';
import {useState,useEffect,useRef} from 'react';
import {Box,Download,Undo2,Redo2,Ruler,Layers,Settings2,ChevronRight,Check,FolderOpen,Save,ArrowUpRight,Search,Info,PanelTop,LayoutGrid,RotateCcw,SlidersHorizontal} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem,SelectGroup,SelectLabel} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Toaster,toast} from 'sonner';
import {defaults,schemas,families,label,thickness,validate,exportBundle,download,Values,starterValues,normalizeValues,legacyKeys,geometry,Part} from '@/lib/cabinet';
import SectionEditor from './SectionEditor';
import {convertBays} from '@/lib/sections';
import CabinetView from './CabinetView';
import OpenSCADView from './OpenSCADView';
import ManufacturingExport from './ManufacturingExport';
import DesignHealth from './DesignHealth';
import FitTargetResult from './FitTargetResult';
import DimensionInput from './DimensionInput';
import SettingHelp from './SettingHelp';
import {Units,formatDimension,isLengthField,mapLengths,restoreLengths} from '@/lib/units';
import {partSection} from '@/lib/selection';
import useProjects from './useProjects';
import {parseDesign,Design} from '@/lib/projects';
import HardwarePicker from './HardwarePicker';
import FitGuide from './FitGuide';
import {sectionOrder,sectionFor,settingsGroup,isAdvanced,inactiveReason,presentFields} from '@/lib/settings';
const titles:Record<string,string>={custom_cabinet_width:'Width',custom_cabinet_height:'Height',custom_cabinet_depth:'Depth',custom_top_style:'Top construction',back_style:'Back construction',joinery_style:'Carcass joinery',carcass_stock:'Carcass stock',custom_carcass_thickness:'Measured thickness',base_style:'Base style',include_worktop:'Add worktop',worktop_thickness:'Worktop thickness',cabinet_layout_mode:'Layout',custom_cabinet_contents:'Contents',custom_drawer_count:'Drawer count',custom_door_count:'Door count',mixed_bay_count:'Number of bays',bottom_width_style:'Bottom panel',cnc_tool_diameter:'CNC cutter diameter',slot_corner_relief:'Shared slot relief',side_relief:'Side-panel relief',router_bit_diameter:'CNC cutter diameter'};
const pretty=(s:string)=>({'legacy_spacing':'Manual spacing','explicit_array':'Manufacturer defined','structural_panel':'Structural panel','panel':'Applied thin panel','tab_slot':'Tab & slot','butt':'Butt joint','dado':'Dado','mixed_bays':'Independent bays','legacy':'Full-width layout','custom_mm':'Measured thickness','custom':'Custom'}[s]||label(s).replace(' nominal',' nominal'));
function Choice({value,onChange,options,id}:{value:string;onChange:(s:string)=>void;options:string[];id?:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger id={id} className='choice'><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o} key={o}>{pretty(o)}</SelectItem>)}</SelectContent></Select>}
function ArrayField({value,onChange,id,fieldKey,units,length,activeCount}:{value:any[];onChange:(v:any)=>void;id:string;fieldKey:string;units:Units;length:boolean;activeCount?:number}){
 const active=activeCount===undefined?value:value.slice(0,activeCount);
 const displayed=length?mapLengths(active,n=>Number(formatDimension(n,units))):active;
 const [draft,setDraft]=useState(JSON.stringify(displayed));const [error,setError]=useState(false);useEffect(()=>setDraft(JSON.stringify(displayed)),[value,units,activeCount]);
 const options=fieldKey==='mixed_bay_types'?['drawers','door','open']:fieldKey.includes('shelf_styles')?['fixed','adjustable']:fieldKey.includes('hinge_sides')?['left','right']:fieldKey.includes('height_modes')?['equal','graduated','custom_weights']:null;
 const flat=value.every(v=>typeof v==='number'||typeof v==='string');
 const update=(i:number,v:any)=>{const a=[...value];a[i]=v;onChange(a)};
 return <>{flat&&<div className='array-grid'>{active.map((v,i)=><label key={i} htmlFor={id+'-'+i}>{fieldKey.startsWith('mixed_bay')?'Bay':fieldKey.startsWith('drawer_bank')?'Bank':'Position'} {i+1}{options?<Choice id={id+'-'+i} value={String(v)} options={Array.from(new Set([...options,String(v)]))} onChange={v=>update(i,v)}/>:length&&typeof v==='number'?<DimensionInput id={id+'-'+i} value={v} units={units} onChange={v=>update(i,v)}/>:<input id={id+'-'+i} type={typeof v==='number'?'number':'text'} step='any' value={v} onChange={e=>{if(typeof v==='number'){if(e.target.value!==''&&Number.isFinite(e.target.valueAsNumber))update(i,e.target.valueAsNumber)}else update(i,e.target.value)}}/>}</label>)}</div>}<details className='array-source' open={!flat}><summary>{flat?(activeCount===undefined?'Edit full array':'Edit active entries'):'Edit rows of values'}{length?' ('+units+')':''}</summary><input id={id} className={error?'invalid':''} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{try{const a=JSON.parse(draft);if(!Array.isArray(a)||a.length>30||(activeCount!==undefined&&a.length!==activeCount))throw Error();setError(false);if(draft!==JSON.stringify(displayed))onChange([...(length?restoreLengths(active,displayed,a,units):a),...(activeCount===undefined?[]:value.slice(activeCount))])}catch{setError(true)}}}/></details>{error&&<small className='error'>Enter a JSON array, for example [1, 1, 2].</small>}</>
}
export default function Home(){
 const [family,setFamily]=useState(0),[values,setValues]=useState<Values>(()=>defaults(0)),[step,setStep]=useState('Sizing'),[interior,setInterior]=useState(false),[exploded,setExploded]=useState(false),[dimensions,setDimensions]=useState(true),[tab,setTab]=useState('model'),[query,setQuery]=useState(''),[exportOpen,setExportOpen]=useState(false),[busy,setBusy]=useState(false),[projectName,setProjectName]=useState('Workshop cart');
 const [units,setUnits]=useState<Units>('mm');
 const stockThickness=family===5?thickness(values,'drawer_stock','custom_drawer_material_thickness'):thickness(values);
 const fmt=(n:number)=>formatDimension(n,units);
 const [selected,setSelected]=useState<string|null>(null);
 const [setupOpen,setSetupOpen]=useState(false);
 const [advanced,setAdvanced]=useState<Record<string,boolean>>({});
 const [past,setPast]=useState<Values[]>([]),[future,setFuture]=useState<Values[]>([]);const input=useRef<HTMLInputElement>(null);const current=useRef({family,values});current.current={family,values};
 const [solved,setSolved]=useState<{key:string;dimensions:Record<string,number>}|null>(null);
 const configKey=JSON.stringify({family,values});const fitActive=family>=5||values.width_basis==='drawer_inside'||values.depth_basis==='drawer_inside';
 const previewValues=solved?.key===configKey?{...values,custom_cabinet_width:solved.dimensions.RESOLVED_CABINET_W,custom_cabinet_height:solved.dimensions.RESOLVED_CABINET_H??values.custom_cabinet_height,custom_cabinet_depth:solved.dimensions.RESOLVED_CARCASS_D}:values;
 const selectable=[...new Map([...geometry(previewValues,false,false),...geometry(previewValues,true,false)].map(p=>[p.id,p])).values()];const selectedPart=selectable.find(p=>p.id===selected);
 const selectPart=(p:Part|null)=>{setSelected(p?.id??null);if(p){setStep(partSection(p));setQuery('')}};
 const fields=presentFields(schemas[family].fields),errors=validate(values);
 const change=(key:string,val:any)=>{setPast(p=>[...p.slice(-49),values]);setFuture([]);setValues(v=>normalizeValues(family,{...v,...(key==='cabinet_layout_mode'&&val==='sections'?{section_nodes:convertBays(v),width_basis:'outside',depth_basis:'outside'}:{}),[key]:val,_starter:'edited'}))};
 function switchFamily(n:number){setFamily(n);setValues(defaults(n));setPast([]);setFuture([]);setProjectName(families[n].name);setStep('Sizing');setQuery('')}
 const undo=()=>{if(past.length){setFuture(f=>[values,...f]);setValues(past[past.length-1]);setPast(p=>p.slice(0,-1))}},redo=()=>{if(future.length){setPast(p=>[...p,values]);setValues(future[0]);setFuture(f=>f.slice(1))}};
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'read_cabinet_configuration',description:'Read the current cabinet family, parameters and envelope validation.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...current.current,validation:validate(current.current.values)})},{signal:lifecycle.signal})).catch(()=>{});return ()=>lifecycle.abort()},[]);
 function field(f:typeof fields[number]){const key=f.key,value=values[key],id='field-'+key+'-'+sectionFor(f); return <div className={'field '+(isAdvanced(f)?'is-advanced ':'')+(typeof value==='boolean'?'toggle-field':'')} key={key}><SettingHelp advanced={isAdvanced(f)} id={id} title={family===3&&key==='door_shelf_count'?'Shelf count':titles[key]??label(key)} help={[family===3&&key==='door_shelf_count'?'Number of internal shelves. Zero shelves makes one open section; each added shelf creates another section.':f.description,f.expression?'Leave blank to calculate automatically ('+f.expression+').':''].filter(Boolean).join(' ')}/>{isLengthField(f)&&!Array.isArray(value)?<DimensionInput id={id} value={value} units={units} automatic={!!f.expression} bounds={f.bounds} onChange={v=>change(key,v)}/>:typeof value==='boolean'?<Switch id={id} checked={value} onCheckedChange={v=>change(key,v)}/>:f.options?<Choice id={id} value={String(value)} onChange={v=>change(key,typeof f.value==='number'?Number(v):v)} options={f.options}/>:Array.isArray(value)?<ArrayField id={id} activeCount={key.startsWith('mixed_bay_')?Number(values.mixed_bay_count):key.startsWith('drawer_bank_')?Number(values.drawer_bank_count):undefined} fieldKey={key} units={units} length={isLengthField(f)} value={value} onChange={v=>change(key,v)}/>:typeof value==='number'?<div className='number-wrap'><input id={id} type='number' value={value} step={f.bounds?.[2]??.1} min={f.bounds?.[0]} max={f.bounds?.[1]} onChange={e=>{if(e.target.value!==''&&Number.isFinite(e.target.valueAsNumber))change(key,e.target.valueAsNumber)}}/></div>:<input id={id} value={String(value??'')} onChange={e=>change(key,e.target.value)}/>}</div>}
 function arrayChange(key:string,i:number,v:any){const a=[...(values[key]??[])];a[i]=v;change(key,a)}
 async function exportFiles(){if(errors.length)return;setBusy(true);try{download(await exportBundle(family,values),'cabinet-workshop.zip');toast.success('OpenSCAD project downloaded');setExportOpen(false)}catch(e){toast.error(String(e))}finally{setBusy(false)}}
 function save(){download(new Blob([JSON.stringify({version:2,engine:5,engineFamily:"modular_organization",bundleRevision:5,displayUnits:units,family,name:projectName,values},null,2)],{type:'application/json'}),'design.cabinet.json');projects.markSaved();toast.success('Design downloaded to your device')}
 function restoreDesign(d:Design){setUnits(d.displayUnits);setFamily(d.family);setValues(d.values);setStep('Sizing');setProjectName(d.name);setPast([]);setFuture([])}
 const projects=useProjects({version:2,engine:5,engineFamily:"modular_organization",bundleRevision:5,family,name:projectName,displayUnits:units,values},restoreDesign);
 async function load(file?:File){if(!file)return;try{if(file.size>1000000)throw Error();const d=parseDesign(JSON.parse(await file.text()));projects.guard(()=>{restoreDesign(d);projects.markSaved(d);toast.success('Design opened')})}catch{toast.error('This file is not a valid Cabinet Workshop design.')}finally{if(input.current)input.current.value=''}}

 const visibleFields=fields.filter(f=>!['cabinet_preset','kitchen_model_code'].includes(f.key));
 const steps=sectionOrder.filter(name=>name==='Hardware'||visibleFields.some(f=>sectionFor(f)===name));
 const sectionFields=visibleFields.filter(f=>sectionFor(f)===step);
 const advancedCount=sectionFields.filter(f=>!inactiveReason(f,values)&&isAdvanced(f)).length;
 const filtered=(query.trim()?visibleFields:sectionFields).filter(f=>!inactiveReason(f,values)&&(query.trim()||advanced[sectionFor(f)]||!isAdvanced(f))&&(f.key+' '+f.section+' '+f.description).toLowerCase().includes(query.toLowerCase()));
 const groups=Array.from(new Set(filtered.map(settingsGroup)));
 function chooseStarter(id:string){setPast(p=>[...p.slice(-49),values]);setFuture([]);setValues(starterValues(family,id,values));if(id==='photo_section_cabinet'){setStep('Structure');setQuery('')}setProjectName(schemas[family].starters.find(p=>p.id===id)?.name??families[family].name);toast.success('Starter loaded — review dimensions and materials')}
 return <main>{projects.dialogs}<Toaster position='bottom-right'/><header className='app-header'><a href='/' className='brand'><span className='brand-icon'><Box size={24}/></span><div>Cabinet<span>WORKSHOP</span></div></a><div className='header-project'><span className='separator'/><input aria-label='Design name' value={projectName} onChange={e=>setProjectName(e.target.value)}/><span className='draft' role='status'>{projects.status}</span></div><div className='header-actions'><button onClick={projects.openRecent}>Recent</button><button onClick={()=>input.current?.click()} title='Open design'><FolderOpen size={17}/><span>Open</span></button><button onClick={save}><Save size={17}/><span>Save design</span></button><button className='primary' onClick={()=>setExportOpen(true)}><Download size={17}/><span>Export project</span></button></div><input type='file' accept='.json' ref={input} hidden onChange={e=>load(e.target.files?.[0])}/></header>
 <div className={'workspace settings-workspace '+(setupOpen?'setup-expanded':'')}><aside className='setup-rail' aria-label='Cabinet setup'><button className='setup-toggle' aria-expanded={setupOpen} aria-controls='cabinet-setup-controls' onClick={()=>setSetupOpen(v=>!v)} title={setupOpen?'Collapse cabinet setup':'Expand cabinet setup'}><Settings2 size={20}/><span>Setup</span><ChevronRight size={16} className={setupOpen?'turned':''}/></button>{setupOpen?<div id='cabinet-setup-controls'><div className='family-picker'><label htmlFor='family'>Cabinet family</label><Select value={String(family)} onValueChange={s=>projects.guard(()=>switchFamily(Number(s)))}><SelectTrigger id='family' className='choice family-choice'><SelectValue/></SelectTrigger><SelectContent>{families.map((f,i)=><SelectItem value={String(i)} key={f.name}>{f.name}</SelectItem>)}</SelectContent></Select><p>{families[family].sub}</p><label htmlFor='units'>Display units</label><Select value={units} onValueChange={v=>setUnits(v as Units)}><SelectTrigger id='units' className='choice'><SelectValue/></SelectTrigger><SelectContent><SelectItem value='mm'>Metric · millimeters</SelectItem><SelectItem value='in'>Imperial · inches</SelectItem></SelectContent></Select><label htmlFor='starter' className='starter-label'>Starter configuration</label><Select value={values._starter??'edited'} onValueChange={id=>projects.guard(()=>chooseStarter(id))}><SelectTrigger id='starter' className='choice starter-choice'><SelectValue/></SelectTrigger><SelectContent><SelectItem value='edited' disabled>Custom · edited configuration</SelectItem>{family===4?<><SelectItem value='default'>Default configuration</SelectItem>{Array.from(new Set(schemas[family].starters.filter(p=>p.id!=='default').map(p=>p.group??'Engine recipes'))).map(group=><SelectGroup key={group}><SelectLabel>{group}</SelectLabel>{schemas[family].starters.filter(p=>p.id!=='default'&&(p.group??'Engine recipes')===group).map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectGroup>)}</>:schemas[family].starters.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select><small className='starter-hint'>{family===4?'Standard sizes use nominal inches and apply editable millimeter settings. Other settings stay in place.':'Engine presets load a complete starting configuration. Save your current design before switching.'}</small></div></div>:<div className='setup-summary'><span>{families[family].name}</span><small>{units}</small></div>}</aside><aside className='config'><div className='config-title'><span className='eyebrow'>CONFIGURATION</span><button title='Reset current family' aria-label='Reset current family' onClick={()=>projects.guard(()=>{setPast(p=>[...p,values]);setFuture([]);setValues(defaults(family));toast.success('Default settings restored')})}><RotateCcw size={16}/></button></div>
 <div className='config-tabs'><div className='section-picker'><label htmlFor='settings-section'>Settings section</label><Select value={step} onValueChange={v=>{setStep(v);setQuery('')}}><SelectTrigger id='settings-section' className='choice'><SelectValue/></SelectTrigger><SelectContent>{steps.map(name=><SelectItem value={name} key={name}>{name}</SelectItem>)}</SelectContent></Select></div>
 <div key={step} className='config-scroll'><div className='settings-heading'><h2>{step}</h2><span>{step==='Hardware'?'Preset library':sectionFields.filter(f=>!inactiveReason(f,values)).length+' settings'}</span></div>{advancedCount>0&&<label className='advanced-control'><Switch checked={!!advanced[step]} onCheckedChange={v=>setAdvanced(a=>({...a,[step]:v}))}/>Show advanced <span>{advancedCount}</span></label>}<div className='search-field'><Search size={16}/><input placeholder='Find any setting…' aria-label='Search all settings' value={query} onChange={e=>setQuery(e.target.value)}/></div>
 {step==='Hardware'&&<HardwarePicker query={query} family={family} apply={patch=>{setPast(p=>[...p.slice(-49),values]);setFuture([]);setValues(normalizeValues(family,{...values,...patch,_starter:'edited'}));toast.success('Hardware settings applied — all values remain editable')}}/>}{step==='Sizing'&&family<5&&<FitGuide family={family} values={values} units={units} change={change} patch={patch=>{setPast(p=>[...p.slice(-49),values]);setFuture([]);setValues(normalizeValues(family,{...values,...patch,_starter:'edited'}))}}/>}
 {step==='Machining'&&<p className='field-note'>Shared settings provide defaults. Material-specific relief and cutter diameters appear with the relevant joints below. A diameter of 0 inherits the shared cutter. Use None where CAM adds relief.</p>}
 {family===4&&step==='Structure'&&values.cabinet_layout_mode==='sections'&&<SectionEditor values={values} thickness={stockThickness} units={units} change={nodes=>change('section_nodes',nodes)}/>}
 {family===4&&step==='Structure'&&values.cabinet_layout_mode==='mixed_bays'&&<div className='note'><Info size={17}/><p>Independent bays are full-height columns, numbered left to right. Increase Bay count to use bays 3 and 4. Each column contains drawers, a door, or open shelves; switch to Sections to split openings horizontally and vertically.</p></div>}
 {groups.map(group=><section key={group} className='settings-group'><h3>{query.trim()?group:group.split(' / ').slice(1).join(' / ')}</h3>{filtered.filter(f=>settingsGroup(f)===group).map(f=>field(f))}</section>)}
 {filtered.length===0&&step!=='Hardware'&&<p className='muted'>{query?'No matching visible settings. Try showing advanced settings.':'Turn on advanced settings to see the controls in this section.'}</p>}
 </div></div><div className='config-footer'><span>Modular Organization</span><strong>v5 · MOI-4</strong></div></aside>
 <section className='design-surface'><div className='surface-header'><div><div className='eyebrow'>{families[family].code} <span>/</span> PARAMETRIC DESIGN</div><h1>{projectName||families[family].name}</h1></div><div className='history'><button onClick={undo} disabled={!past.length} aria-label='Undo'><Undo2 size={18}/></button><button onClick={redo} disabled={!future.length} aria-label='Redo'><Redo2 size={18}/></button></div></div>
 <div className='part-inspector'><label htmlFor='part-selector'>Edit a component</label><select id='part-selector' value={selectedPart?.id??''} onChange={e=>selectPart(selectable.find(p=>p.id===e.target.value)??null)}><option value=''>Select in the schematic or choose here…</option>{selectable.map(p=><option key={p.id} value={p.id}>{p.name} · {p.id}</option>)}</select>{selectedPart&&<span>{partSection(selectedPart)} settings opened · dimensions are schematic estimates</span>}</div><DesignHealth family={family} values={values}/><FitTargetResult units={units} family={family} values={values} onSolved={dimensions=>setSolved({key:configKey,dimensions})}/><Tabs value={tab} onValueChange={setTab} className='view-tabs'><div className='canvas-toolbar'><TabsList className='view-switch'><TabsTrigger value='model'><Box size={16}/>Schematic</TabsTrigger><TabsTrigger value='render'><Layers size={16}/>OpenSCAD render</TabsTrigger><TabsTrigger value='specs'><Ruler size={16}/>Design summary</TabsTrigger></TabsList><span className='schematic-label'>{tab==='model'?(fitActive&&solved?.key!==configKey?'Configured envelope · fit not calculated':'Instant preview'):tab==='render'?'Actual geometry':'Configuration'}</span></div><TabsContent value='model' className='model-content'><div className='preview-scope'><div><strong>Quick schematic · approximate</strong><span>{family===6?'Solid envelopes only; skeletonized sides, cleats and hardware need the exact render.':'Joinery, screw guides and drawer-divider grooves are resolved in the exact render.'}</span></div><button onClick={()=>setTab('render')}>Inspect exact geometry</button></div><div className='display-controls'><label><Switch checked={interior} onCheckedChange={setInterior}/>Show interior</label><label><Switch checked={exploded} onCheckedChange={setExploded}/>Exploded</label><button className={dimensions?'selected':''} onClick={()=>setDimensions(v=>!v)} aria-pressed={dimensions}><Ruler size={16}/><span>Dimensions</span></button></div>{errors.length?<div className='validation-panel'><Info/><h2>Check your dimensions</h2>{errors.map(e=><p key={e}>{e}</p>)}</div>:<CabinetView selected={selected} onSelect={selectPart} units={units} values={previewValues} interior={interior} exploded={exploded} dimensions={dimensions}/>}<div className='model-caption'><span className='material-dot'/>{fmt(stockThickness)} {units} {family===5?'drawer wall':'carcass'} stock<span className='caption-divider'/> {pretty(family===5?values.drawer_joinery_style:values.joinery_style??'butt')}<span className='model-index'>01 / ASSEMBLY</span></div></TabsContent>
 <TabsContent value='render' forceMount hidden={tab!=='render'} className='native-content'><OpenSCADView selected={fitActive&&solved?.key!==configKey?undefined:selectedPart} parts={fitActive&&solved?.key!==configKey?[]:selectable} onSelect={selectPart} family={family} values={values} active={tab==='render'}/></TabsContent><TabsContent value='specs' className='spec-content'><span className='eyebrow'>DESIGN SPECIFICATION</span><h2>{projectName}</h2><dl>{[['Family',families[family].name],[family===5?'Drawer box envelope':family===6?'Equipment frame envelope':'Carcass envelope',`${fmt(previewValues.custom_cabinet_width)} × ${fmt(previewValues.custom_cabinet_height)} × ${fmt(previewValues.custom_cabinet_depth)} ${units}`],[family===5?'Drawer wall stock':'Carcass stock',`${fmt(stockThickness)} ${units}`],[family>=5?'Design basis':'Layout',pretty(family===5?values.drawer_design_basis:family===6?values.sizing_mode:values.cabinet_layout_mode??'legacy')],[family===5?'Box joinery':'Carcass joinery',pretty(family===5?values.drawer_joinery_style:values.joinery_style??'butt')],[family===5?'Bottom joint':'Back',pretty(family===5?values.drawer_bottom_joinery:values.back_style??'panel')],[family>=5?'Mount':'Base',pretty(family===5?values.drawer_mount:family===6?values.mount_mode:values.base_style??'flat')],[family===5?'Decorative face':'Worktop',family===5?pretty(values.drawer_face_style):values.include_worktop?`${fmt(values.worktop_thickness)} ${units}`:'None']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className='note'><Info size={20}/><p>This is a configuration summary, not a cut list. Export the project and use the shared OpenSCAD engine for exact parts, machining geometry, and the bill of materials.</p></div><button className='primary' onClick={()=>setExportOpen(true)}>Export OpenSCAD project <ArrowUpRight size={16}/></button></TabsContent></Tabs>
 <div className='summary-bar'><div><span>WIDTH</span><strong>{fmt(previewValues.custom_cabinet_width)}<small>{units}</small></strong></div><div><span>HEIGHT</span><strong>{fmt(previewValues.custom_cabinet_height)}<small>{units}</small></strong></div><div><span>{family===5?'BOX DEPTH':family===6?'FRAME DEPTH':'CARCASS DEPTH'}</span><strong>{fmt(previewValues.custom_cabinet_depth)}<small>{units}</small></strong></div><div className='depth-metric' hidden={family>=5}><span>INTERIOR DEPTH</span><strong>{fmt(previewValues.custom_cabinet_depth-(values.back_style==='structural_panel'?thickness(values):0))}<small>{units}</small></strong></div><div className='status'>{errors.length?<><Info size={17}/>Check dimensions</>:<><Check size={17}/>Input ranges checked</>}</div></div><div className='bottom-note'><Info size={14}/><span>Schematic dimensions are estimates. OpenSCAD resolves joints, holes, dividers, cleats and side cutouts. Check the exact render before exporting.</span></div></section></div>
 <Dialog open={exportOpen} onOpenChange={setExportOpen}><DialogContent className='export-dialog'><DialogHeader><span className='export-icon'><Download/></span><DialogTitle>Take your design to the workshop</DialogTitle><DialogDescription>Generate manufacturing files or download your editable OpenSCAD project. Sources, SVGs and manufacturing reports use millimeters.</DialogDescription></DialogHeader><ManufacturingExport units={units} family={family} values={values} name={projectName} invalid={!!errors.length}/><div className='export-includes'><h3>OpenSCAD project · ZIP</h3><p><Check size={16}/> Your selected cabinet and all current settings</p><p><Check size={16}/> Shared geometry and manufacturing layouts</p><p><Check size={16}/> BOM export script and editable design file</p></div><div className='note'><Info size={18}/><p>Open the included .scad file in OpenSCAD to render exact geometry and export cut, pocket, engraving, or BOM outputs. Use the OpenSCAD render tab to inspect actual 3D geometry here. The manufacturing package above evaluates these outputs directly in your browser.</p></div>{errors.map(e=><p className='error' key={e}>{e}</p>)}<button className='primary download-button' disabled={busy||!!errors.length} onClick={exportFiles}><Download size={18}/>{busy?'Preparing project…':'Download project'}</button></DialogContent></Dialog>
 </main>
}
