'use client';
import {useState} from 'react';
import {AlertTriangle,Check,ClipboardCopy,Download,Info,LoaderCircle,Printer,XCircle} from 'lucide-react';
import {cutListCsv,MATERIAL_NAMES,Plan} from '@/lib/analysis';
import {download,Values} from '@/lib/cabinet';
import {formatShop,Units} from '@/lib/units';
import type {Analysis} from './useEngineAnalysis';

const esc=(s:unknown)=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]!));
export function sheetEstimate(area:number,values:Values){
 const w=Number(values.stock_width)||2440,h=Number(values.stock_height)||1220;
 return Math.max(1,Math.ceil(area/(w*h*0.8)));
}
function areaText(mm2:number,units:Units){return units==='in'?(mm2/92903.04).toFixed(1)+' ft²':(mm2/1e6).toFixed(2)+' m²'}

export function StatusChip({analysis,onClick}:{analysis:Analysis;onClick?:()=>void}){
 const p=analysis.plan,stale=analysis.planKey!==analysis.key;
 const errors=p?.issues.filter(i=>i.severity==='error').length??0,warnings=p?.issues.filter(i=>i.severity==='warning').length??0;
 const busy=analysis.state==='waiting'||analysis.state==='running';
 const [cls,icon,text]=analysis.state==='invalid'?['bad',<XCircle size={15} key='i'/>,'Fix highlighted dimensions']
  :!p&&busy?['busy',<LoaderCircle size={15} className='render-spinner' key='i'/>,'Checking with OpenSCAD…']
  :!p?['bad',<XCircle size={15} key='i'/>,analysis.error||'Engine check unavailable']
  :errors?['bad',<XCircle size={15} key='i'/>,errors+' problem'+(errors>1?'s':'')+' to fix']
  :warnings?['warn',<AlertTriangle size={15} key='i'/>,'Fits · '+warnings+' note'+(warnings>1?'s':'')]
  :['ok',<Check size={15} key='i'/>,'Parts fit · checked by OpenSCAD'];
 return <button type='button' className={'status-chip is-'+cls+(stale&&p?' is-stale':'')} onClick={onClick} aria-live='polite'
  title={stale&&busy?'Updating for your latest change…':'Open the cut list and fit report'}>
  {stale&&busy&&p?<LoaderCircle size={15} className='render-spinner'/>:icon}<span>{text}</span>
 </button>;
}

function Dim({mm,units}:{mm:number;units:Units}){
 return <span className='dim' title={Number.isFinite(mm)?mm.toFixed(2)+' mm':''}>{Number.isFinite(mm)?formatShop(mm,units):'—'}</span>;
}

export function printablePlan(plan:Plan,name:string,units:Units,values:Values){
 const f=(mm:number)=>esc(formatShop(mm,units));
 const rows=plan.cut.map(c=>`<tr><td>${esc(c.name)}<small>${esc(c.ids.join(', '))}</small></td><td>${c.qty}</td><td>${esc(MATERIAL_NAMES[c.material]??c.material)}</td><td>${f(c.thickness)}</td><td>${f(c.width)}</td><td>${f(c.height)}</td><td><small>${esc(c.notes)}</small></td></tr>`).join('');
 const drawers=plan.drawers.map(d=>`<tr><td>${esc(d.id)}</td><td>${f(d.opening.w)} × ${f(d.opening.h)}</td><td>${f(d.box.w)} × ${f(d.box.h)} × ${f(d.box.d)}</td><td>${f(d.inside.w)} × ${f(d.inside.h)} × ${f(d.inside.d)}</td><td>${f(d.side)} / ${f(d.vertical)}</td></tr>`).join('');
 const mats=plan.materials.map(m=>`<li>${esc(MATERIAL_NAMES[m.material]??m.material)} · ${f(m.thickness)}: ${m.parts} parts, ${areaText(m.area,units)}, about ${sheetEstimate(m.area,values)} sheet(s)</li>`).join('');
 return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(name)} · cut list</title><style>
 body{font:12px/1.4 Arial,sans-serif;color:#1d343d;margin:24px}h1{font-size:20px;margin:0 0 4px}h2{font-size:14px;margin:18px 0 6px}
 table{border-collapse:collapse;width:100%}th,td{border-bottom:1px solid #ccd5d8;padding:4px 6px;text-align:left;vertical-align:top}th{background:#eef2f3}
 small{display:block;color:#5d6f75}p{margin:2px 0;color:#5d6f75}</style></head><body>
 <h1>${esc(name)}</h1><p>Cut list generated by Claude Cabinet Workshop from the OpenSCAD engine. Sizes are finished cut sizes${units==='in'?' rounded to the nearest 1/32 in (CSV keeps full millimeter precision)':' in millimeters'}.</p>
 ${plan.outside?`<p>Outside: ${f(plan.outside.w)} W × ${f(plan.outside.h)} H × ${f(plan.outside.d)} D</p>`:''}
 <h2>Materials</h2><ul>${mats}</ul><h2>Parts (${plan.partCount})</h2>
 <table><thead><tr><th>Part</th><th>Qty</th><th>Material</th><th>Thick</th><th>Cut W</th><th>Cut H</th><th>Notes</th></tr></thead><tbody>${rows}</tbody></table>
 ${drawers?`<h2>Drawer fit</h2><table><thead><tr><th>Drawer</th><th>Opening W × H</th><th>Box W × H × D</th><th>Inside W × H × D</th><th>Clearance side / vertical</th></tr></thead><tbody>${drawers}</tbody></table>`:''}
 <script>window.onload=()=>window.print()</script></body></html>`;
}

export default function PlanPanel({analysis,units,name,values}:{analysis:Analysis;units:Units;name:string;values:Values}){
 const plan=analysis.plan,stale=analysis.planKey!==analysis.key;
 const [copied,setCopied]=useState(false);
 if(analysis.state==='invalid')return <div className='plan-empty'><XCircle/><h2>Fix the dimensions first</h2><p>{analysis.error}</p></div>;
 if(!plan)return <div className='plan-empty'>{analysis.state==='failed'?<><XCircle/><h2>The engine check could not run</h2><p>{analysis.error}</p></>:<><LoaderCircle className='render-spinner'/><h2>Building the cut list…</h2><p>OpenSCAD is calculating every part from your settings. This usually takes a few seconds.</p></>}</div>;
 const errors=plan.issues.filter(i=>i.severity==='error'),notes=plan.issues.filter(i=>i.severity!=='error');
 const filename=(name||'cabinet').replace(/[^a-z0-9_-]+/gi,'-');
 const byMaterial=new Map<string,typeof plan.cut>();
 for(const c of plan.cut){const k=c.material+'|'+c.thickness;byMaterial.set(k,[...(byMaterial.get(k)??[]),c])}
 return <div className={'plan'+(stale?' is-stale':'')}>
  {stale&&<p className='plan-stale' role='status'><LoaderCircle size={15} className='render-spinner'/> Updating for your latest change…</p>}
  <div className='plan-actions'>
   <div>
    <strong>{plan.partCount} parts</strong>
    {plan.outside&&<span> · outside <Dim mm={plan.outside.w} units={units}/> W × <Dim mm={plan.outside.h} units={units}/> H × <Dim mm={plan.outside.d} units={units}/> D</span>}
   </div>
   <button onClick={async()=>{try{await navigator.clipboard.writeText(cutListCsv(plan));setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{}}}><ClipboardCopy size={15}/>{copied?'Copied':'Copy CSV'}</button>
   <button onClick={()=>download(new Blob([cutListCsv(plan)],{type:'text/csv'}),filename+'-cut-list.csv')}><Download size={15}/>CSV</button>
   <button onClick={()=>{const url=URL.createObjectURL(new Blob([printablePlan(plan,name,units,values)],{type:'text/html'}));window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),60000)}}><Printer size={15}/>Print</button>
  </div>
  {errors.length>0&&<section className='plan-issues is-error' role='alert'>
   <h3><XCircle size={17}/> Fix before building</h3>
   {errors.map((i,k)=><p key={k}><strong>{i.code.replaceAll('_',' ').toLowerCase()}</strong>{i.message}</p>)}
  </section>}
  {notes.length>0&&<details className='plan-issues is-warning'>
   <summary><AlertTriangle size={16}/> {notes.length} build note{notes.length>1?'s':''} to review</summary>
   {notes.map((i,k)=><p key={k}><strong>{i.code.replaceAll('_',' ').toLowerCase()}</strong>{i.message}</p>)}
  </details>}
  {!errors.length&&<p className='plan-ok'><Check size={16}/> The engine’s fit and machining checks passed for this design. Measure your actual sheet thickness and make a test cut before production.</p>}
  <h3 className='plan-heading'>Sheet goods</h3>
  <div className='material-cards'>
   {plan.materials.map(m=><div key={m.material+m.thickness}>
    <strong>{MATERIAL_NAMES[m.material]??m.material}</strong>
    <span><Dim mm={m.thickness} units={units}/> thick · {m.parts} part{m.parts>1?'s':''}</span>
    <small>{areaText(m.area,units)} · about {sheetEstimate(m.area,values)} sheet{sheetEstimate(m.area,values)>1?'s':''}</small>
   </div>)}
  </div>
  {(()=>{const byT=new Map<number,number>();for(const m of plan.materials)byT.set(m.thickness,(byT.get(m.thickness)??0)+m.area);
   return byT.size<plan.materials.length?<p className='sheet-totals'><strong>If cut from the same sheets:</strong> {[...byT.entries()].sort((a,b)=>b[1]-a[1]).map(([t,a])=>formatShop(t,units)+(units==='mm'?' mm':'')+' ≈ '+sheetEstimate(a,values)).join(' · ')}</p>:null})()}
  <p className='field-note'>Sheet counts are area estimates with 20% waste on {Number(values.stock_width)||2440} × {Number(values.stock_height)||1220} mm stock (Stock width and height in Output), not a nested layout.</p>
  <h3 className='plan-heading'>Cut list</h3>
  <div className='review-table cut-table'>
   <table>
    <thead><tr><th>Part</th><th>Qty</th><th>Cut W</th><th>Cut H</th><th>Notes</th></tr></thead>
    {[...byMaterial.entries()].map(([k,rows])=><tbody key={k}>
     <tr className='group-row'><th colSpan={5}>{MATERIAL_NAMES[rows[0].material]??rows[0].material} · <Dim mm={rows[0].thickness} units={units}/></th></tr>
     {rows.map((c,i)=><tr key={i}>
      <td>{c.name}<small>{c.ids.join(', ')}</small></td>
      <td>{c.qty}</td>
      <td><Dim mm={c.width} units={units}/></td>
      <td><Dim mm={c.height} units={units}/></td>
      <td><small>{c.notes.replaceAll(';','; ')}</small></td>
     </tr>)}
    </tbody>)}
   </table>
  </div>
  {plan.drawers.length>0&&<>
   <h3 className='plan-heading'>Drawer fit</h3>
   <div className='review-table'>
    <table>
     <thead><tr><th>Drawer</th><th>Opening</th><th>Box (outside)</th><th>Usable inside</th><th>Clearance</th><th/></tr></thead>
     <tbody>{plan.drawers.map(d=><tr key={d.id} className={d.ok?'':'is-bad'}>
      <td>{d.id}</td>
      <td><Dim mm={d.opening.w} units={units}/> × <Dim mm={d.opening.h} units={units}/></td>
      <td><Dim mm={d.box.w} units={units}/> × <Dim mm={d.box.h} units={units}/> × <Dim mm={d.box.d} units={units}/></td>
      <td><Dim mm={d.inside.w} units={units}/> × <Dim mm={d.inside.h} units={units}/> × <Dim mm={d.inside.d} units={units}/></td>
      <td><small>side <Dim mm={d.side} units={units}/> · top/bottom <Dim mm={d.vertical} units={units}/></small></td>
      <td>{d.ok?<Check size={16} aria-label='Fits'/>:<XCircle size={16} aria-label={d.problem}/>}</td>
     </tr>)}</tbody>
    </table>
   </div>
   <p className='field-note'>W × H × D. Clearance is per side: slide or runner space at each side, and running space above and below the box.</p>
  </>}
  {plan.sections.length>0&&<>
   <h3 className='plan-heading'>Section openings</h3>
   <div className='review-table'><table><thead><tr><th>Section</th><th>Contents</th><th>Clear opening W × H</th></tr></thead>
    <tbody>{plan.sections.map(s=><tr key={s.id}><td>{s.id}</td><td>{s.contents}</td><td><Dim mm={s.w} units={units}/> × <Dim mm={s.h} units={units}/></td></tr>)}</tbody></table></div>
  </>}
  {plan.doors.length>0&&<>
   <h3 className='plan-heading'>Doors</h3>
   <div className='review-table'><table><thead><tr><th>Door</th><th>Size W × H</th><th>Mount</th><th>Hinge side</th></tr></thead>
    <tbody>{plan.doors.map(d=><tr key={d.id}><td>{d.id}</td><td><Dim mm={d.w} units={units}/> × <Dim mm={d.h} units={units}/></td><td>{d.mount.replaceAll('_',' ')}</td><td>{d.hinge}</td></tr>)}</tbody></table></div>
  </>}
  {plan.shelves.length>0&&<>
   <h3 className='plan-heading'>Shelves</h3>
   <div className='review-table'><table><thead><tr><th>Shelf</th><th>Type</th><th>Cut width</th><th>Depth</th></tr></thead>
    <tbody>{plan.shelves.map(s=><tr key={s.id}><td>{s.id}</td><td>{s.style}</td><td><Dim mm={s.cut} units={units}/>{s.span!==undefined&&s.span!==s.cut?<small>span <Dim mm={s.span} units={units}/></small>:null}</td><td><Dim mm={s.depth} units={units}/></td></tr>)}</tbody></table></div>
  </>}
  {plan.hardware.length>0&&<>
   <h3 className='plan-heading'>Hardware</h3>
   <ul className='hardware-list'>{plan.hardware.map(h=><li key={h.id}><strong>{h.qty}</strong> {h.id.replaceAll('_',' ')}{h.note&&<small>{h.note}</small>}</li>)}</ul>
  </>}
  <p className='field-note'><Info size={13}/> Cut sizes come directly from the OpenSCAD engine (the same run that produces the SVG layouts). {units==='in'?'Inch sizes are rounded to 1/32 in; hover a size for exact millimeters.':'Hover a size for two-decimal precision.'} Checked in {analysis.seconds.toFixed(1)} s.</p>
 </div>;
}
