'use client';
import {useEffect,useRef,useState} from 'react';
import {collapseSection,selectedSectionIds,leaf,sectionRects,sectionRoot,treeErrors,type SectionNode} from '@/lib/sections';
import DimensionInput from './DimensionInput';
import type {Units} from '@/lib/units';
import {formatDimension,formatShop} from '@/lib/units';
export default function SectionEditor({values,thickness,units,change}:{values:Record<string,any>;thickness:number;units:Units;change:(nodes:SectionNode[])=>void}){
 const [selected,setSelected]=useState(0),[draft,setDraft]=useState<SectionNode[]|null>(null);
 const drag=useRef<{id:number;previous:number;start:number;axis:'x'|'z';nodes:SectionNode[];rects:ReturnType<typeof sectionRects>;scale:number}|null>(null);
 const svg=useRef<SVGSVGElement>(null),nodes=(draft??values.section_nodes) as SectionNode[],root=sectionRoot(values,thickness),rects=sectionRects(nodes,root,thickness),errors=treeErrors(nodes),id=Math.min(selected,nodes.length-1),node=nodes[id];
 const valid=rects.length&&rects.every(r=>Number.isFinite(r.w)&&Number.isFinite(r.h)&&r.w>=60&&r.h>=60);
 const commit=(next:SectionNode[])=>{setDraft(null);change(next)};
 const edit=(index:number,value:any)=>{const next=structuredClone(nodes);(next[id] as any)[index]=value;commit(next)};
 const split=(axis:'x'|'z',count:number)=>{if(nodes.length+count>31)return;const next=structuredClone(nodes);next[id][2]=axis;next[id][10]='panel';for(let j=0;j<count;j++)next.push(leaf(id,j,node[5],node[6]));commit(next)};
 const highlighted=errors.length?new Set<number>():selectedSectionIds(nodes,id);
 function finish(cancel=false){if(drag.current){drag.current=null;if(!cancel&&draft)commit(draft);else setDraft(null)}}
 const format=(v:number)=>formatDimension(v,units)+' '+units;
 // SVG units per screen pixel, so labels stay readable whatever the cabinet size.
 const [unit,setUnit]=useState(root.w/300);
 useEffect(()=>{const el=svg.current;if(!el)return;const measure=()=>{if(el.clientWidth)setUnit(root.w/el.clientWidth)};measure();const o=new ResizeObserver(measure);o.observe(el);return ()=>o.disconnect()},[root.w,errors.length,valid]);
 return <section className='section-editor' aria-label='Section layout editor'><h3>Section layout</h3><p>Select an opening to add drawers, doors or shelves. Split a section left/right or top/bottom. Drag a divider to resize its neighbors, or enter a size below.</p>
 {!errors.length&&valid?<svg ref={svg} className='section-diagram' viewBox={`0 0 ${root.w} ${root.h}`} role='group' aria-label='Cabinet front, click a section' onPointerMove={e=>{const d=drag.current;if(!d)return;const delta=((d.axis==='x'?e.clientX:e.clientY)-d.start)*d.scale;const size=(r:typeof rects[number])=>d.axis==='x'?r.w:r.h;const before=size(d.rects[d.previous]),after=size(d.rects[d.id]),movement=Math.max(60-before,Math.min(after-60,delta));const next=structuredClone(d.nodes);const parent=next[d.id][0];next.forEach((n,k)=>{if(n[0]===parent&&n[3]==='weight')n[4]=size(d.rects[k]);});next[d.previous][3]='weight';next[d.id][3]='weight';next[d.previous][4]=before+movement;next[d.id][4]=after-movement;setDraft(next)}} onPointerUp={()=>finish()} onPointerCancel={()=>finish(true)}>
 <rect width={root.w} height={root.h} fill='#8c6743'/>
 {rects.filter(r=>nodes[r.id][2]==='leaf').map(r=>{const n=nodes[r.id],x=r.x-root.x,y=root.h-(r.z-root.z)-r.h,weights=Array.from({length:n[6]},(_,k)=>n[7]==='custom_weights'?n[9][k]:n[7]==='graduated'?1+k*n[8]:1),fraction=(k:number)=>weights.slice(0,k+1).reduce((a,b)=>a+b,0)/weights.reduce((a,b)=>a+b,0),label=n[5]==='drawers'?`${n[6]} drawer${n[6]===1?'':'s'}`:n[5]==='doors'?`${n[6]} door${n[6]===1?'':'s'}`:n[6]?`${n[6]} shelves`:'Open';return <g key={r.id} role='button' tabIndex={0} data-section-id={r.id} aria-pressed={highlighted.has(r.id)} aria-label={`Section ${r.id+1}: ${label}, ${format(r.w)} wide, ${format(r.h)} high`} onClick={()=>setSelected(r.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(r.id)}}}><rect x={x+1} y={y+1} width={Math.max(1,r.w-2)} height={Math.max(1,r.h-2)} fill={highlighted.has(r.id)?'#d8e9f4':'#f5eadb'} stroke={highlighted.has(r.id)?'#146390':'#a6815a'} strokeWidth={highlighted.has(r.id)?5:2}/>{Array.from({length:n[5]==='drawers'?Math.max(0,n[6]-1):n[5]==='doors'&&n[6]===2?1:0},(_,k)=>n[5]==='doors'?<line key={k} x1={x+r.w/2} x2={x+r.w/2} y1={y+4} y2={y+r.h-4} stroke='#a6815a'/>:<line key={k} x1={x+4} x2={x+r.w-4} y1={y+r.h*fraction(k)} y2={y+r.h*fraction(k)} stroke='#a6815a'/>)}{(()=>{const size=units==='mm'?`${Math.round(r.w)} × ${Math.round(r.h)} mm`:`${formatShop(r.w,units)} × ${formatShop(r.h,units)}`,fit=(px:number,text:string)=>Math.min(px*unit,r.w*0.9/(text.length*0.56));return <><text x={x+r.w/2} y={y+r.h/2} textAnchor='middle' fontSize={fit(13,label)} fontWeight={600} fill='#263b48'>{label}</text><text x={x+r.w/2} y={y+r.h/2+15*unit} textAnchor='middle' fontSize={fit(11,size)} fill='#4a6470'>{size}</text></>})()}</g>})}
 {rects.filter(r=>r.id>0&&nodes[r.id][1]>0).map(r=>{const p=nodes[nodes[r.id][0]],pr=rects[nodes[r.id][0]],axis=p[2] as 'x'|'z',gap=p[10]==='none'?0:thickness,x=axis==='x'?r.x-root.x-gap/2:pr.x-root.x,y=axis==='z'?root.h-(r.z-root.z+r.h+gap/2):root.h-(pr.z-root.z+pr.h);return <line key={'split'+r.id} className={'split-handle '+axis} x1={x} x2={axis==='x'?x:x+pr.w} y1={y} y2={axis==='x'?y+pr.h:y} stroke='transparent' strokeWidth={Math.max(12,root.w/55)} onPointerDown={e=>{e.preventDefault();e.stopPropagation();const previous=nodes.findIndex(n=>n[0]===nodes[r.id][0]&&n[1]===nodes[r.id][1]-1);const matrix=svg.current!.getScreenCTM();drag.current={id:r.id,previous,start:axis==='x'?e.clientX:e.clientY,axis,nodes:structuredClone(nodes),rects,scale:matrix?1/(axis==='x'?matrix.a:matrix.d):1};(e.target as Element).setPointerCapture(e.pointerId);setSelected(nodes[r.id][0])}}/>})}
 </svg>:<p role='alert'>{errors[0]??'A section is too small. Reduce fixed sizes, increase cabinet dimensions, or adjust the proportions.'}</p>}
 <label>Selected section<select id='section-selection' value={id} onChange={e=>setSelected(Number(e.target.value))}>{nodes.map((n,i)=><option key={i} value={i}>Section {i+1} · {n[2]==='leaf'?n[5]:n[2]==='x'?'left/right split':'top/bottom split'}</option>)}</select></label>
 {rects[id]&&<p className='section-size'>{format(rects[id].w)} wide × {format(rects[id].h)} high</p>}
 {node&&<>
 {id!==0&&<div className='section-control-row'><label>Size mode<select value={node[3]} onChange={e=>{const next=structuredClone(nodes),axis=nodes[node[0]][2],size=(index:number)=>axis==='x'?rects[index]?.w:rects[index]?.h;if(e.target.value==='weight'){next.forEach((n,i)=>{if(n[0]===node[0]&&n[3]==='weight')n[4]=size(i)??n[4]});}next[id][3]=e.target.value as SectionNode[3];next[id][4]=size(id)??node[4];commit(next)}}><option value='weight'>Proportional</option><option value='mm'>Fixed dimension</option></select></label><label>{node[3]==='mm'?'Clear opening size':'Size weight'}{node[3]==='mm'?<DimensionInput id='section-fixed-size' value={node[4]} units={units} onChange={n=>edit(4,n??1)}/>:<input type='number' min='.1' step='.1' value={node[4]} onChange={e=>edit(4,Number(e.target.value))}/>}</label></div>}
 {node[2]==='leaf'?<>
 <label>Contents<select value={node[5]} onChange={e=>{const next=structuredClone(nodes),n=next[id];n[5]=e.target.value as SectionNode[5];n[6]=n[5]==='open'?0:n[5]==='doors'?2:3;n[9]=Array(Math.max(1,n[6])).fill(1);commit(next)}}><option value='drawers'>Drawer bank</option><option value='doors'>Doors</option><option value='open'>Open / shelves</option></select></label>
 <label>{node[5]==='drawers'?'Drawer count':node[5]==='doors'?'Door count':'Shelf count'}<input type='number' min={node[5]==='open'?0:1} max={node[5]==='doors'?2:8} value={node[6]} onChange={e=>{const next=structuredClone(nodes);next[id][6]=Number(e.target.value);while(next[id][9].length<Math.min(8,next[id][6]))next[id][9].push(1);commit(next)}}/></label>
 {node[5]==='doors'&&<label>Shelves behind doors<input type='number' min='0' max='8' value={node[11]} onChange={e=>edit(11,Number(e.target.value))}/></label>}
 {node[5]==='drawers'&&<><label>Drawer heights<select value={node[7]} onChange={e=>edit(7,e.target.value)}><option value='equal'>Equal</option><option value='graduated'>Graduated</option><option value='custom_weights'>Custom weights</option></select></label>{node[7]==='graduated'&&<label>Growth per drawer<input type='number' min='0' step='.1' value={node[8]} onChange={e=>edit(8,Number(e.target.value))}/></label>}{node[7]==='custom_weights'&&<div><span>Height weights, top to bottom</span>{node[9].slice(0,node[6]).map((w,i)=><label key={i}>Drawer {i+1}<input type='number' min='.1' step='.1' value={w} onChange={e=>{const next=structuredClone(node[9]);next[i]=Number(e.target.value);edit(9,next)}}/></label>)}</div>}</>}
 <div className='section-actions'><button type='button' disabled={nodes.length>29} onClick={()=>split('x',2)}>Split left / right</button><button type='button' disabled={nodes.length>29} onClick={()=>split('z',2)}>Split top / bottom</button><button type='button' disabled={nodes.length>28} onClick={()=>split('x',3)}>Three columns</button></div>
 </>:<><label>Construction at this split<select value={node[10]} onChange={e=>edit(10,e.target.value)}><option value='panel'>Full-depth panel</option>{node[2]==='z'&&<option value='rail'>Front support rail (80 mm)</option>}<option value='none'>Layout boundary only</option></select></label><button type='button' onClick={()=>{commit(collapseSection(nodes,id));setSelected(Math.min(id,nodes.length-1))}}>Replace split with one opening</button><p>Paired doors share one opening. Drawer-count settings do not add separator panels. Undo restores a replaced split.</p></>}
 </>}
 <p className='section-construction-note'>Section supports are butt-fit blanks; fit them with suitable brackets, cleats or shop-drilled fasteners. Transfer cabinet-side slide/hinge holes during fitting. Drawer-box joints and door machining use the existing settings. Fixed sizes measure clear openings, excluding separators.</p>
 </section>;
}
