'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Design,Recent,PROJECT_STORE,recentRecords,upsertRecent} from '@/lib/projects';
export default function useProjects(design:Design,onRestore:(d:Design)=>void){
 const [ready,setReady]=useState(false),[records,setRecords]=useState<Recent[]>([]),[recovery,setRecovery]=useState<Recent|null>(null),[recentOpen,setRecentOpen]=useState(false),[pending,setPending]=useState<(()=>void)|null>(null),[status,setStatus]=useState('Starting recovery…');
 const id=useRef(''),baseline=useRef(JSON.stringify(design)),latest=useRef(design),list=useRef<Recent[]>([]),restore=useRef(onRestore);latest.current=design;restore.current=onRestore;
 const [savedKey,setSavedKey]=useState(baseline.current);const dirty=JSON.stringify(design)!==savedKey;
 function persist(){if(!id.current)return;try{const next=upsertRecent(recentRecords(localStorage.getItem(PROJECT_STORE)),{id:id.current,updated:new Date().toISOString(),design:latest.current});localStorage.setItem(PROJECT_STORE,JSON.stringify(next));list.current=next;setRecords(next);setStatus('Autosaved on this browser')}catch{setStatus('Autosave unavailable · download your design')}}
 useEffect(()=>{id.current=crypto.randomUUID();try{const a=recentRecords(localStorage.getItem(PROJECT_STORE));list.current=a;setRecords(a);if(a.length){setRecovery(a[0]);setStatus('Recovery available')}else setReady(true)}catch{setStatus('Recovery could not be read · save a copy');setReady(true)}},[]);
 useEffect(()=>{if(!ready)return;setStatus('Saving locally…');const timer=setTimeout(persist,650);return()=>clearTimeout(timer)},[design.family,design.name,design.values,design.displayUnits,ready]);
 useEffect(()=>{const flush=()=>{if(ready&&document.visibilityState==='hidden')persist()};const unload=(e:BeforeUnloadEvent)=>{if(ready)persist();if(dirty){e.preventDefault();e.returnValue=''}};document.addEventListener('visibilitychange',flush);window.addEventListener('beforeunload',unload);return()=>{document.removeEventListener('visibilitychange',flush);window.removeEventListener('beforeunload',unload)}},[ready,dirty]);
 const guard=(action:()=>void)=>{const run=()=>{if(ready)persist();id.current=crypto.randomUUID();action()};if(dirty)setPending(()=>run);else run()};
 const apply=(r:Recent)=>{id.current=r.id;restore.current(r.design);setSavedKey(JSON.stringify(r.design));setReady(true);setRecovery(null);setRecentOpen(false)};
 const dialogs=<><Dialog open={!!recovery} onOpenChange={open=>{if(!open){setRecovery(null);setReady(true)}}}><DialogContent><DialogHeader><DialogTitle>Resume your last design?</DialogTitle><DialogDescription>{recovery?.design.name} · {recovery?new Date(recovery.updated).toLocaleString():''}. Recovery copies are stored only in this browser.</DialogDescription></DialogHeader><button className='primary' onClick={()=>recovery&&apply(recovery)}>Resume design</button><button onClick={()=>{setRecovery(null);setReady(true)}}>Start a new design</button></DialogContent></Dialog><Dialog open={!!pending} onOpenChange={o=>{if(!o)setPending(null)}}><DialogContent><DialogHeader><DialogTitle>Replace the current design?</DialogTitle><DialogDescription>You have changes since your last downloaded or opened design. A local copy will remain in Recent designs when browser storage is available.</DialogDescription></DialogHeader><button className='primary' onClick={()=>{const action=pending;setPending(null);action?.()}}>Continue</button><button onClick={()=>setPending(null)}>Keep editing</button></DialogContent></Dialog><Dialog open={recentOpen} onOpenChange={setRecentOpen}><DialogContent><DialogHeader><DialogTitle>Recent designs</DialogTitle><DialogDescription>Up to 10 local projects on this browser. Download important designs for a portable backup.</DialogDescription></DialogHeader><div className='recent-list'>{records.length?records.map(r=><button key={r.id} onClick={()=>guard(()=>apply(r))}><strong>{r.design.name||'Untitled cabinet'}</strong><small>{new Date(r.updated).toLocaleString()}</small></button>):<p>No recovered designs yet.</p>}</div></DialogContent></Dialog></>;
 return {guard,status,dialogs,openRecent:()=>{if(ready)persist();setRecentOpen(true)},markSaved:(d?:Design)=>setSavedKey(JSON.stringify(d??latest.current))};
}
