// Plain-language help and option labels for the settings people use most.
// The engine's own descriptions are kept for everything not listed here.
// Every statement below was checked against the engine's dimension reports.
export const HELP:Record<string,string>={
 cabinet_width:'Overall outside width of the carcass, side to side. Worktop overhangs and face-frame overlays are not included.',
 cabinet_height:'Height of the carcass sides, including any toe kick. A worktop, base mounting plate, casters or levelers add to the overall height.',
 cabinet_depth:'Outside depth of the carcass sides, front edge to back edge. An applied back panel is fixed behind this depth.',
 cabinet_nominal_depth:'Finished front-to-back depth including the face frame. The carcass is made shallower by the frame so the total matches this value.',
 width_basis:'Outside: you enter the cabinet width. Drawer inside: the engine solves the cabinet width from the drawer interior you need.',
 depth_basis:'Outside: you enter the cabinet depth. Drawer inside: the engine solves the depth from the drawer interior you need.',
 kitchen_family:'Base, wall or tall cabinet. This sets defaults such as mounting; every value remains editable.',
 cabinet_contents:'What fills the cabinet: a stack of drawers, doors, or drawers over doors (combo).',
 cabinet_layout_mode:'Single column fills the whole opening. Side-by-side bays split it into full-height columns. Sections lets you split openings in both directions.',
 drawer_count:'Number of drawers stacked in the drawer region.',
 door_count:'Number of doors side by side. With three or more doors, a partition can be added behind each gap for hinge mounting.',
 door_shelf_count:'Number of shelves behind the doors.',
 shelf_style:'Fixed shelves are joined into the sides like the bottom panel. Adjustable shelves sit on pins in drilled hole rows.',
 top_style:'Full top panel, or a front and a rear stretcher (common under a worktop).',
 top_stretcher_depth:'Front-to-back width of each top stretcher.',
 back_style:'Applied panel is a thin back fixed over the rear edges. Structural panel is carcass-thickness and joined in. Stretchers are rear rails. Drawers and shelves always stop in front of the rear construction.',
 back_stretcher_height:'Height of each rear stretcher rail.',
 back_stretcher_inset:'How far the rear stretchers sit in from the back edge of the sides.',
 joinery_style:'How the bottom, top, shelves and partitions join the sides. Dado and tab & slot are cut by the CNC layouts; butt and screw joints need shop fastening.',
 base_style:'Toe kick gives a recessed plinth; flat sits directly on the floor; leveling feet and casters are added below the cabinet height.',
 custom_toe_kick_height:'Height of the recessed toe kick.',
 custom_toe_kick_setback:'How far the toe kick is recessed behind the cabinet front.',
 custom_bottom_above_toe:'Height of the underside of the cabinet bottom above the floor. Normally equal to the toe-kick height.',
 include_worktop:'Adds a separate work surface on top of the carcass. It is not part of the carcass height.',
 worktop_thickness:'Thickness of the work surface.',
 worktop_front_overhang:'How far the worktop projects past the cabinet front.',
 worktop_back_overhang:'How far the worktop projects past the cabinet back.',
 worktop_side_overhang:'How far the worktop projects past each side.',
 front_facing_style:'A face frame is a hardwood-style frame on the cabinet front. Frameless cabinets show the panel edges.',
 face_frame_construction:'Surface strips are glued onto the carcass front. Back-dadoed strips are pocketed on the back so the side, bottom and top edges nest into the frame for positive registration.',
 face_frame_side_stile_width:'Width of the vertical frame members at each side.',
 face_frame_top_rail_width:'Height of the horizontal frame member at the top.',
 face_frame_bottom_rail_width:'Height of the horizontal frame member at the bottom.',
 face_frame_mid_rail_width:'Height of the middle rail.',
 face_frame_center_stile_width:'Width of the center stile between a pair of doors.',
 include_face_frame_center_stile:'Adds a vertical frame member between a pair of doors. It is only used where it cannot cross a drawer front.',
 front_mount_style:'Overlay fronts sit in front of the cabinet or face frame. Inset fronts sit inside the opening, flush with the front.',
 overlay_width_style:'Partial overlay leaves the side-panel edges visible. Full overlay covers them.',
 front_edge_reveal:'Gap between the outer edges of the fronts and the cabinet edge (or the frame opening for inset fronts).',
 drawer_gap:'Gap between neighbouring drawer fronts.',
 door_gap:'Gap between neighbouring doors.',
 drawer_mount:'Metal slides need side clearance for the slide; wood runners are cut from sheet stock and screwed to the sides; none gives a free-fit box.',
 drawer_height_mode:'Equal drawers, graduated drawers (each lower drawer taller), or custom proportions.',
 drawer_height_weights:'One positive number per drawer, top drawer first. Heights are shared in these proportions.',
 drawer_graduated_step:'How much taller each drawer is than the one above it, as a fraction of the top drawer (0.25 = 25% per step).',
 drawer_vertical_clearance:'Running space above and below each drawer box inside its opening.',
 drawer_back_clearance:'Space left between the back of each drawer box and the rear construction.',
 front_setback:'How far each drawer box starts behind the cabinet front. Inset fronts push the boxes back automatically.',
 drawer_bottom_inset:'Height of the drawer bottom above the lower edge of the box sides.',
 drawer_joinery_style:'How the drawer box front and back join the sides.',
 drawer_bottom_joinery:'Butt bottoms fit between the four walls. Dado bottoms sit in grooves cut in all four walls.',
 include_drawer_faces:'Adds separate decorative fronts in front of the drawer boxes.',
 include_drawer_separators:'Adds a full-width horizontal rail between neighbouring drawers. Only for a single drawer column; side-by-side drawer banks have partitions instead.',
 include_mixed_bay_partitions:'Full-depth panels between independent bays. Drawers, shelves and door hinges next to a bay boundary mount to them, so leave this on unless every bay is open.',
 drawer_bank_count:'Splits the drawer region into side-by-side columns separated by partitions.',
 drawer_bank_layout_mode:'Shared uses the same drawer count and heights in every column. Independent lets each column differ.',
 metal_slide_length:'Nominal length of the drawer slides you will buy. The engine limits it to the drawer box depth.',
 metal_slide_clearance_per_side:'Space each slide needs between the drawer box and the cabinet side (often 12.7 mm / 1/2 in). Check the slide data sheet.',
 metal_slide_front_setback:'Distance from the cabinet front to the front of the slide.',
 metal_slide_envelope_height:'Height of the slide body. Drawer boxes shorter than this are reported as an error.',
 wood_rail_height:'Height of the fixed rail screwed to the cabinet side.',
 wood_rail_front_setback:'Distance from the cabinet front to the front of the wood rail.',
 wood_drawer_runner_height:'Height of the runner fixed to the drawer side.',
 hinge_style:'35 mm cup hinges get a cup pocket in the door plus plate holes. Screw-on hinges get mounting holes only. None leaves hinge drilling to you.',
 hinge_count:'Hinges per door. Use more for tall or heavy doors.',
 hinge_end_offset:'Distance from the top and bottom edge of the door to the center of the end hinges.',
 hinge_cup_depth:'Depth of the 35 mm cup bore in the back of the door. Check the hinge data sheet.',
 hinge_plate_center_from_front:'Distance from the cabinet front to the center of the hinge mounting-plate holes.',
 adjustable_shelf_hole_spacing:'Vertical spacing of the shelf-pin holes (32 mm is the European system standard).',
 adjustable_shelf_front_setback:'Distance from the cabinet front to the front row of shelf-pin holes. Pins that would hit a hinge mounting plate are left out.',
 adjustable_shelf_rear_setback:'Distance from the back of the cabinet to the rear row of shelf-pin holes.',
 adjustable_shelf_hole_diameter:'Diameter of the shelf-pin holes (usually 5 mm).',
 adjustable_shelf_hole_type:'Through holes are cut with the parts. Blind holes are exported as a separate drilling (pocket) layout.',
 include_door_hinge_partitions:'With three or more doors, adds a structural partition behind each gap for hinge mounting. Inset doors close against the partition.',
 extend_top_drawer_face_to_top:'Lets the top drawer face run up to the cabinet top edge. The box itself is unchanged.',
 fronts_cover_bottom_lip:'Lets the lowest front cover the front edge of the bottom panel. The box stays inside the opening, so the lowest box is shorter than its face.',
 cabinet_mount_style:'Floor-standing or wall-hung. Wall cabinets cannot use a floor base.',
 bottom_width_style:'Between the sides is the usual construction. Full width puts the sides on top of the bottom, which helps carry caster loads.',
 module_type:'What this stackable module holds: drawers, a door, or open shelves.',
 stack_interface_depth:'Height of the interlocking lip where one module sits on the next.',
 sizing_mode:'Fit around equipment sizes the stand from the device plus clearances. Manual uses the overall size you enter.',
 device_width:'Width of the device the stand must hold.',
 device_depth:'Depth of the device the stand must hold.',
 device_height:'Height of the device the stand must hold.',
 side_clearance:'Free space at each side of the device on its tray.',
 top_clearance:'Free space above the device.',
 tray_count:'Number of pull-out trays.',
 tray_inset:'How far the trays sit back from the stand front when closed.',
 tray_extension:'How far the trays travel out. Fixed runners do not travel.',
 slide_type:'Side-mount slides let trays pull out. Fixed runners hold a removable service shelf with no travel.',
 mount_mode:'Freestanding, or wall-mounted on a French cleat.',
 drawer_divider_height:'Height of the drawer organizer dividers. It must be lower than the drawer’s inside height.',
 drawer_divider_layout_mode:'Equal count spaces the dividers evenly; custom positions uses the positions you enter.',
 carcass_stock:'Sheet thickness for the carcass. Nominal sizes convert the fraction exactly (3/4 in = 19.05 mm); real plywood is often thinner, so measure it and choose Measured thickness when joint fit matters.',
 back_stock:'Sheet thickness for the back.',
 drawer_stock:'Sheet thickness for the drawer box sides, front and back.',
 drawer_bottom_stock:'Sheet thickness for the drawer bottoms.',
 drawer_front_stock:'Thickness of the decorative drawer faces.',
 door_stock:'Thickness of the doors.',
 face_frame_stock:'Thickness of the face-frame stock.',
};
const OPTIONS:Record<string,Record<string,string>>={
 base_style:{toe_kick:'Toe kick',flat:'Flat base',leveling_feet:'Leveling feet',casters:'Casters'},
 top_style:{stretchers:'Front & rear stretchers',full:'Full top panel'},
 shelf_style:{fixed:'Fixed (joined)',adjustable:'Adjustable (shelf pins)'},
 cabinet_contents:{drawers:'Drawers',doors:'Doors',combo:'Drawers over doors',open:'Open shelves'},
 joinery_style:{butt:'Butt joint',screw:'Screwed butt joint',dado:'Dado (grooved)',tab_slot:'Tab & slot (CNC)'},
 drawer_joinery_style:{butt:'Butt joint',screw:'Screwed butt joint',dado:'Dado (grooved)',tab_slot:'Tab & slot (CNC)'},
 front_mount_style:{overlay:'Overlay',inset_flush:'Inset (flush)'},
 front_facing_style:{face_frame:'Face frame',none:'Frameless'},
 overlay_width_style:{partial:'Partial overlay',full:'Full overlay'},
 hinge_style:{none:'None (drill by hand)',euro_35mm:'35 mm cup hinge',screw_holes:'Screw-on hinge (holes only)'},
 drawer_mount:{metal_slides:'Metal side-mount slides',wood_rails:'Wood runners',none:'None (free fit)'},
 drawer_height_mode:{equal:'Equal',graduated:'Graduated (taller lower drawers)',custom_weights:'Custom proportions'},
 cabinet_layout_mode:{legacy:'Single column',mixed_bays:'Side-by-side bays',sections:'Sections (split openings)'},
 face_frame_construction:{segmented_surface:'Surface-mounted strips',segmented_back_dado:'Back-dadoed strips (registered)'},
 face_frame_mid_rail_mode:{none:'None',combo_auto:'Automatic (drawer/door boundary)',custom:'Custom height'},
 drawer_bottom_joinery:{butt:'Between the walls (butt)',dado:'In grooves (dado)'},
 bottom_width_style:{joined:'Between the sides',full_width:'Full width under the sides'},
 cabinet_mount_style:{floor:'Floor standing',wall:'Wall hung'},
 module_type:{drawers:'Drawers',open:'Open shelves',door:'Door'},
 kitchen_family:{base:'Base cabinet',wall:'Wall cabinet',tall:'Tall cabinet'},
 slide_type:{side_mount:'Side-mount slides',fixed_runner:'Fixed runners (no travel)'},
 sizing_mode:{equipment:'Fit around equipment',manual:'Enter overall size'},
 mount_mode:{freestanding:'Freestanding',wall_mount_french_cleat:'Wall-mounted French cleat'},
 back_style:{panel:'Applied thin panel',structural_panel:'Structural panel',stretchers:'Rear stretchers',none:'Open back',auto:'Automatic'},
 drawer_bank_layout_mode:{shared:'Same in every column',independent:'Set per column'},
 adjustable_shelf_hole_type:{through:'Through holes',blind:'Blind holes'},
 width_basis:{outside:'Outside size',drawer_inside:'Drawer inside size'},
 depth_basis:{outside:'Outside size',drawer_inside:'Drawer inside size'},
 drawer_divider_layout_mode:{equal_count:'Equal count',custom_positions:'Custom positions'},
};
export const optionLabel=(key:string,option:string)=>OPTIONS[key]?.[option];
